#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Mpirun    Meshing
runApplication blockMesh

# Simulation
runApplication $(getApplication)

# Post-process
paraFoam -touchAll

#------------------------------------------------------------------------------
