#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf \
    processor* \
    constant/*/polyMesh \
    constant/extendedFeatureEdgeMesh \
    constant/triSurface/*.eMesh

#------------------------------------------------------------------------------
